# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.12.3' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
     - name: Upload a Build Artifact

  uses: actions/upload-artifact@v3.1.2

  with:

    # Artifact name

    name: # optional, default is artifact

    # A file, directory or wildcard pattern that describes what to upload

    path: 

    # The desired behavior if no files are found using the provided path.

Available Options:

  warn: Output a warning but do not fail the action

  error: Fail the action with an error message

  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn

    # Duration after which artifact will expire in days. 0 means using default retention.

Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # optional
